# Generated by Django 5.0.7 on 2025-06-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_bug_created_by_bug_modified_at_bug_modified_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bug',
            name='changeset_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bug',
            name='ticket_number',
            field=models.CharField(editable=False, max_length=20, null=True, unique=True),
        ),
    ]
